# Generated by Django 4.2.10 on 2024-03-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_reservation_time_slot_reservation_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisines',
            field=models.ManyToManyField(default=['Uzbek'], related_name='restaurants', to='restaurant.cuisine'),
        ),
    ]
