# Generated by Django 4.2.10 on 2024-03-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_remove_restaurant_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
