# Generated by Django 4.2.10 on 2024-03-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_menucategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisines',
            field=models.ManyToManyField(blank=True, null=True, related_name='restaurants', to='restaurant.cuisine'),
        ),
    ]
