# Generated by Django 4.2.10 on 2024-03-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_restaurant_cuisines'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='num_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
