# Generated by Django 4.2.11 on 2024-03-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_restaurant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='closing_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisines',
            field=models.ManyToManyField(blank=True, null=True, related_name='restaurants', to='restaurant.cuisine'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_halal',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='num_reviews',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='opening_time',
            field=models.TimeField(null=True),
        ),
    ]
