# Generated by Django 4.2.11 on 2024-03-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_reservation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisines',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='restaurant.cuisine'),
        ),
        migrations.AlterUniqueTogether(
            name='menucategory',
            unique_together={('slug', 'restaurant')},
        ),
    ]
