# Generated by Django 4.2.11 on 2024-03-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_alter_reservation_special_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='photos',
            field=models.ImageField(blank=True, upload_to='restaurant/restaurant_photos/', verbose_name='Restaurant image'),
        ),
    ]
