# Generated by Django 4.2.11 on 2024-03-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_alter_restaurant_photos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='photos',
            field=models.ImageField(blank=True, upload_to='restaurant_photos/', verbose_name='Restaurant image'),
        ),
        migrations.AlterField(
            model_name='table',
            name='time_slots',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
