# Generated by Django 4.2.10 on 2024-03-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'admin'), (1, 'user')], default=1),
        ),
    ]
