# Generated by Django 4.2.10 on 2024-03-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'superadmin'), (1, 'admin'), (2, 'user')], default=2),
        ),
    ]